import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/export_bundle.dart';
import 'i_renderer.dart';

class PdfRenderer implements IRenderer {
  @override
  String get extension => 'pdf';

  @override
  String get mimeType => 'application/pdf';

  @override
  Future<Uint8List> render(ExportBundle bundle) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(level: 0, text: 'CashPilot Financial Report'),
          pw.Paragraph(text: 'Generated on: ${bundle.auditTrail.generatedAt}'),
          pw.Paragraph(text: 'Generated by: ${bundle.auditTrail.generatedBy}'),
          
          pw.Header(level: 1, text: 'VAT Summary'),
          pw.TableHelper.fromTextArray(
            headers: ['Label', 'Value'],
            data: [
              ['Net Amount', bundle.vatSummary.netAmount.toStringAsFixed(2)],
              ['VAT Rate', '${(bundle.vatSummary.vatRate * 100).toStringAsFixed(0)}%'],
              ['VAT Amount', bundle.vatSummary.vatAmount.toStringAsFixed(2)],
              ['Gross Total', bundle.vatSummary.grossTotal.toStringAsFixed(2)],
            ],
          ),

          pw.Header(level: 1, text: 'Expenses'),
          pw.TableHelper.fromTextArray(
            headers: ['Date', 'Title', 'Amount', 'Category'],
            data: bundle.expenses.map((e) => [
              e.date.toIso8601String().substring(0, 10),
              e.title,
              (e.amount / 100.0).toStringAsFixed(2),
              e.categoryId ?? 'N/A'
            ]).toList(),
          ),
        ],
      ),
    );

    return await pdf.save();
  }
}
