// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/generate_tokens.dart

import 'package:flutter/material.dart';

class AppTokens {
  AppTokens._();

  // ============================================
  // COLORS
  // ============================================
  static const Color brandPrimary = Color(0xFF1F9E63);
  static const Color brandPrimaryLight = Color(0xFF48C98C);
  static const Color brandPrimaryDark = Color(0xFF0C7A4A);
  static const Color brandSecondary = Color(0xFF2DA8E8);
  static const Color brandAccent = Color(0xFFB05AF2);
  static const Color brandGold = Color(0xFFC7A46A);
  static const Color neutralWhite = Color(0xFFFFFFFF);
  static const Color neutralBlack = Color(0xFF000000);
  static const Color neutralGrey50 = Color(0xFFF9FAFB);
  static const Color neutralGrey100 = Color(0xFFF3F4F6);
  static const Color neutralGrey200 = Color(0xFFE5E7EB);
  static const Color neutralGrey300 = Color(0xFFD1D5DB);
  static const Color neutralGrey400 = Color(0xFF9CA3AF);
  static const Color neutralGrey500 = Color(0xFF6B7280);
  static const Color neutralGrey600 = Color(0xFF4B5563);
  static const Color neutralGrey700 = Color(0xFF374151);
  static const Color neutralGrey800 = Color(0xFF161618);
  static const Color neutralGrey900 = Color(0xFF0E0E10);
  static const Color semanticSuccess = Color(0xFF32C75A);
  static const Color semanticWarning = Color(0xFFF6A100);
  static const Color semanticDanger = Color(0xFFE33D38);
  static const Color semanticCaution = Color(0xFFFF9500);
  static const Color semanticInfo = Color(0xFF248BFF);
  static const Color themeLightBackground = neutralWhite;
  static const Color themeLightSurface = neutralGrey50;
  static const Color themeLightSurfaceVariant = neutralGrey100;
  static const Color themeLightTextPrimary = neutralBlack;
  static const Color themeLightTextSecondary = neutralGrey700; // Darker for better contrast
  static const Color themeLightBorder = neutralGrey200;
  static const Color themeDarkBackground = Color(0xFF3C3C3C);
  static const Color themeDarkSurface = Color(0xFF3C3C3C);
  static const Color themeDarkSurfaceVariant = Color(0xFF4A4A4A);
  static const Color themeDarkSurfaceElevated = Color(0xFF555555);
  static const Color themeDarkTextPrimary = neutralWhite;
  static const Color themeDarkTextSecondary = Color(0xFFE5E5E5); // Near-white for better contrast
  static const Color themeDarkTextOnPrimary = neutralWhite;
  static const Color themeDarkBorder = Color(0xFF4A4A4A);

  // ============================================
  // SPACING
  // ============================================
  static const double spaceXs = 4.0;
  static const double spaceSm = 8.0;
  static const double spaceMd = 12.0;
  static const double spaceLg = 16.0;
  static const double spaceXl = 24.0;
  static const double spaceXxl = 32.0;
  static const double spaceSection = 48.0;

  // ============================================
  // RADIUS
  // ============================================
  static const double radiusXs = 4.0;
  static const double radiusSm = 8.0;
  static const double radiusMd = 12.0;
  static const double radiusLg = 16.0;
  static const double radiusXl = 24.0;
  static const double radiusPill = 999.0;

  // ============================================
  // MOTION
  // ============================================
  static const Duration durationFast = Duration(milliseconds: 120);
  static const Duration durationNormal = Duration(milliseconds: 200);
  static const Duration durationSlow = Duration(milliseconds: 350);

  // ============================================
  // GRADIENTS
  // ============================================
  static const List<Color> dangerGradient = [semanticDanger, Color(0xFFFF6B6B)];
  static const List<Color> successGradient = [brandPrimary, brandPrimaryLight];

}
